[package]
name = "fits_view_client"
version = "0.1.0"
edition = "2021"

[features]
default = []
wgpu = []
snapshot = []

[dependencies]
bytemuck = { version = "1.13", features = ["derive"] }
egui = "0.22"
eframe = { version = "0.22", default-features = false, features = ["wgpu"] }
egui-wgpu = "0.22"
wgpu = "0.16"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.24"
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1.37", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
serde_json = "1.0"
tempfile = "3.0"
